/*
 * @Author: Kanata You 
 * @Date: 2021-02-05 13:19:40 
 * @Last Modified by: Kanata You
 * @Last Modified time: 2021-02-05 14:37:49
 */

export type influenceFlow = {
  source_gid: number;
  target_gid: number;
  count: number;
};

export type influenceEachYear = {
  year: number;
  flow: influenceFlow[];
}

const influenceByYear: influenceEachYear[] = [{
  "year": 1930,
  "flow": [{
    "source_gid": 18,
    "target_gid": 14,
    "count": 4
  }, {
    "source_gid": 18,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 9
  }, {
    "source_gid": 11,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 12
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 34
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 32
  }, {
    "source_gid": 3,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 3
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 10
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 14,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 3,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 3,
    "count": 1
  }]
}, {
  "year": 1940,
  "flow": [{
    "source_gid": 8,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 128
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 22
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 244
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 100
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 5
  }, {
    "source_gid": 18,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 36
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 16
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 16
  }, {
    "source_gid": 1,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 6
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 14,
    "count": 14
  }, {
    "source_gid": 4,
    "target_gid": 14,
    "count": 3
  }, {
    "source_gid": 18,
    "target_gid": 16,
    "count": 5
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 10
  }, {
    "source_gid": 5,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 9
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 8
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 7
  }, {
    "source_gid": 1,
    "target_gid": 10,
    "count": 5
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 5
  }, {
    "source_gid": 17,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 3
  }, {
    "source_gid": 8,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 5,
    "count": 7
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 5,
    "target_gid": 5,
    "count": 5
  }, {
    "source_gid": 3,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 5,
    "count": 3
  }, {
    "source_gid": 6,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 13,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 13,
    "target_gid": 4,
    "count": 1
  }]
}, {
  "year": 1950,
  "flow": [{
    "source_gid": 4,
    "target_gid": 4,
    "count": 161
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 463
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 282
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 4
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 70
  }, {
    "source_gid": 4,
    "target_gid": 1,
    "count": 15
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 24
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 282
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 21
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 86
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 36
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 72
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 174
  }, {
    "source_gid": 5,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 10
  }, {
    "source_gid": 15,
    "target_gid": 15,
    "count": 221
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 134
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 94
  }, {
    "source_gid": 18,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 39
  }, {
    "source_gid": 11,
    "target_gid": 0,
    "count": 13
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 11,
    "target_gid": 11,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 5,
    "target_gid": 5,
    "count": 9
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 65
  }, {
    "source_gid": 0,
    "target_gid": 14,
    "count": 23
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 26
  }, {
    "source_gid": 17,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 14
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 3
  }, {
    "source_gid": 10,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 16
  }, {
    "source_gid": 4,
    "target_gid": 14,
    "count": 11
  }, {
    "source_gid": 18,
    "target_gid": 14,
    "count": 11
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 17
  }, {
    "source_gid": 15,
    "target_gid": 18,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 10,
    "count": 5
  }, {
    "source_gid": 18,
    "target_gid": 16,
    "count": 20
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 33
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 30
  }, {
    "source_gid": 4,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 5,
    "target_gid": 15,
    "count": 5
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 25
  }, {
    "source_gid": 4,
    "target_gid": 8,
    "count": 4
  }, {
    "source_gid": 0,
    "target_gid": 13,
    "count": 3
  }, {
    "source_gid": 14,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 6,
    "count": 3
  }, {
    "source_gid": 0,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 11
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 7
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 4
  }, {
    "source_gid": 4,
    "target_gid": 17,
    "count": 6
  }, {
    "source_gid": 16,
    "target_gid": 17,
    "count": 3
  }, {
    "source_gid": 1,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 13,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 18,
    "count": 3
  }, {
    "source_gid": 5,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 10,
    "count": 15
  }, {
    "source_gid": 14,
    "target_gid": 10,
    "count": 5
  }, {
    "source_gid": 15,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 14,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 18,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 1,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 5,
    "count": 5
  }, {
    "source_gid": 17,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 8,
    "count": 5
  }, {
    "source_gid": 0,
    "target_gid": 18,
    "count": 5
  }, {
    "source_gid": 5,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 17,
    "count": 4
  }, {
    "source_gid": 6,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 9,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 9,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 17,
    "count": 8
  }, {
    "source_gid": 6,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 9,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 9,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 2,
    "target_gid": 6,
    "count": 1
  }]
}, {
  "year": 1960,
  "flow": [{
    "source_gid": 6,
    "target_gid": 6,
    "count": 6
  }, {
    "source_gid": 4,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 3,
    "count": 18
  }, {
    "source_gid": 10,
    "target_gid": 3,
    "count": 4
  }, {
    "source_gid": 15,
    "target_gid": 5,
    "count": 4
  }, {
    "source_gid": 5,
    "target_gid": 5,
    "count": 3
  }, {
    "source_gid": 16,
    "target_gid": 5,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 15,
    "target_gid": 19,
    "count": 7
  }, {
    "source_gid": 18,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 2,
    "target_gid": 19,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 8
  }, {
    "source_gid": 15,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 15,
    "count": 2320
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 386
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 19
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 415
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 6
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 430
  }, {
    "source_gid": 17,
    "target_gid": 18,
    "count": 6
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 82
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 655
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 90
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 249
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 138
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 77
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 80
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 37
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 15
  }, {
    "source_gid": 3,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 10,
    "count": 9
  }, {
    "source_gid": 5,
    "target_gid": 18,
    "count": 4
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 179
  }, {
    "source_gid": 15,
    "target_gid": 10,
    "count": 52
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 51
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 54
  }, {
    "source_gid": 10,
    "target_gid": 0,
    "count": 7
  }, {
    "source_gid": 0,
    "target_gid": 13,
    "count": 71
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 14
  }, {
    "source_gid": 11,
    "target_gid": 11,
    "count": 8
  }, {
    "source_gid": 0,
    "target_gid": 11,
    "count": 3
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 13
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 9
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 126
  }, {
    "source_gid": 1,
    "target_gid": 10,
    "count": 19
  }, {
    "source_gid": 15,
    "target_gid": 18,
    "count": 22
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 78
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 292
  }, {
    "source_gid": 17,
    "target_gid": 6,
    "count": 4
  }, {
    "source_gid": 10,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 10,
    "count": 17
  }, {
    "source_gid": 18,
    "target_gid": 10,
    "count": 10
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 49
  }, {
    "source_gid": 5,
    "target_gid": 15,
    "count": 8
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 16
  }, {
    "source_gid": 13,
    "target_gid": 13,
    "count": 61
  }, {
    "source_gid": 4,
    "target_gid": 1,
    "count": 14
  }, {
    "source_gid": 3,
    "target_gid": 15,
    "count": 6
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 23
  }, {
    "source_gid": 16,
    "target_gid": 17,
    "count": 27
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 27
  }, {
    "source_gid": 18,
    "target_gid": 3,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 11,
    "count": 9
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 8
  }, {
    "source_gid": 17,
    "target_gid": 13,
    "count": 6
  }, {
    "source_gid": 0,
    "target_gid": 18,
    "count": 16
  }, {
    "source_gid": 18,
    "target_gid": 13,
    "count": 10
  }, {
    "source_gid": 13,
    "target_gid": 15,
    "count": 9
  }, {
    "source_gid": 15,
    "target_gid": 17,
    "count": 10
  }, {
    "source_gid": 4,
    "target_gid": 17,
    "count": 13
  }, {
    "source_gid": 10,
    "target_gid": 17,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 10,
    "count": 3
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 7
  }, {
    "source_gid": 16,
    "target_gid": 4,
    "count": 3
  }, {
    "source_gid": 11,
    "target_gid": 0,
    "count": 7
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 11
  }, {
    "source_gid": 18,
    "target_gid": 16,
    "count": 14
  }, {
    "source_gid": 11,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 17,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 17,
    "count": 11
  }, {
    "source_gid": 19,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 16,
    "count": 10
  }, {
    "source_gid": 0,
    "target_gid": 10,
    "count": 4
  }, {
    "source_gid": 6,
    "target_gid": 2,
    "count": 3
  }, {
    "source_gid": 2,
    "target_gid": 2,
    "count": 2
  }, {
    "source_gid": 17,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 2,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 13,
    "count": 3
  }, {
    "source_gid": 1,
    "target_gid": 13,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 16,
    "count": 7
  }, {
    "source_gid": 0,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 4
  }, {
    "source_gid": 2,
    "target_gid": 15,
    "count": 14
  }, {
    "source_gid": 0,
    "target_gid": 14,
    "count": 14
  }, {
    "source_gid": 5,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 7
  }, {
    "source_gid": 1,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 1,
    "target_gid": 14,
    "count": 3
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 14,
    "count": 11
  }, {
    "source_gid": 17,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 13,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 0,
    "count": 3
  }, {
    "source_gid": 17,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 17,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 7,
    "count": 4
  }, {
    "source_gid": 10,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 14,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 6,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 19,
    "target_gid": 15,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 2,
    "target_gid": 6,
    "count": 3
  }, {
    "source_gid": 1,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 13,
    "count": 3
  }, {
    "source_gid": 3,
    "target_gid": 13,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 6,
    "count": 2
  }]
}, {
  "year": 1970,
  "flow": [{
    "source_gid": 18,
    "target_gid": 15,
    "count": 92
  }, {
    "source_gid": 15,
    "target_gid": 15,
    "count": 3495
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 127
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 31
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 74
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 15
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 19
  }, {
    "source_gid": 0,
    "target_gid": 17,
    "count": 7
  }, {
    "source_gid": 14,
    "target_gid": 17,
    "count": 5
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 67
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 255
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 33
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 420
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 102
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 62
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 59
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 229
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 13
  }, {
    "source_gid": 11,
    "target_gid": 11,
    "count": 8
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 495
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 39
  }, {
    "source_gid": 5,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 22
  }, {
    "source_gid": 14,
    "target_gid": 1,
    "count": 3
  }, {
    "source_gid": 16,
    "target_gid": 0,
    "count": 4
  }, {
    "source_gid": 7,
    "target_gid": 15,
    "count": 5
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 13
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 26
  }, {
    "source_gid": 15,
    "target_gid": 11,
    "count": 19
  }, {
    "source_gid": 1,
    "target_gid": 11,
    "count": 3
  }, {
    "source_gid": 13,
    "target_gid": 15,
    "count": 100
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 24
  }, {
    "source_gid": 13,
    "target_gid": 13,
    "count": 232
  }, {
    "source_gid": 0,
    "target_gid": 18,
    "count": 18
  }, {
    "source_gid": 19,
    "target_gid": 7,
    "count": 10
  }, {
    "source_gid": 7,
    "target_gid": 7,
    "count": 10
  }, {
    "source_gid": 2,
    "target_gid": 7,
    "count": 4
  }, {
    "source_gid": 5,
    "target_gid": 7,
    "count": 5
  }, {
    "source_gid": 15,
    "target_gid": 7,
    "count": 12
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 31
  }, {
    "source_gid": 18,
    "target_gid": 7,
    "count": 14
  }, {
    "source_gid": 10,
    "target_gid": 11,
    "count": 5
  }, {
    "source_gid": 17,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 15,
    "count": 53
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 47
  }, {
    "source_gid": 15,
    "target_gid": 14,
    "count": 13
  }, {
    "source_gid": 16,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 3,
    "target_gid": 15,
    "count": 6
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 18
  }, {
    "source_gid": 17,
    "target_gid": 18,
    "count": 8
  }, {
    "source_gid": 19,
    "target_gid": 19,
    "count": 12
  }, {
    "source_gid": 15,
    "target_gid": 19,
    "count": 30
  }, {
    "source_gid": 1,
    "target_gid": 18,
    "count": 11
  }, {
    "source_gid": 15,
    "target_gid": 18,
    "count": 24
  }, {
    "source_gid": 0,
    "target_gid": 13,
    "count": 22
  }, {
    "source_gid": 10,
    "target_gid": 7,
    "count": 4
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 4
  }, {
    "source_gid": 6,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 2,
    "target_gid": 19,
    "count": 4
  }, {
    "source_gid": 18,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 22
  }, {
    "source_gid": 18,
    "target_gid": 17,
    "count": 4
  }, {
    "source_gid": 3,
    "target_gid": 3,
    "count": 7
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 35
  }, {
    "source_gid": 2,
    "target_gid": 15,
    "count": 9
  }, {
    "source_gid": 11,
    "target_gid": 15,
    "count": 5
  }, {
    "source_gid": 5,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 13,
    "target_gid": 0,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 7
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 26
  }, {
    "source_gid": 17,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 7,
    "count": 3
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 10
  }, {
    "source_gid": 17,
    "target_gid": 10,
    "count": 3
  }, {
    "source_gid": 1,
    "target_gid": 14,
    "count": 5
  }, {
    "source_gid": 0,
    "target_gid": 14,
    "count": 10
  }, {
    "source_gid": 4,
    "target_gid": 13,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 17,
    "count": 10
  }, {
    "source_gid": 4,
    "target_gid": 11,
    "count": 4
  }, {
    "source_gid": 15,
    "target_gid": 17,
    "count": 6
  }, {
    "source_gid": 14,
    "target_gid": 4,
    "count": 3
  }, {
    "source_gid": 13,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 10,
    "count": 3
  }, {
    "source_gid": 8,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 10,
    "count": 38
  }, {
    "source_gid": 4,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 1,
    "target_gid": 10,
    "count": 18
  }, {
    "source_gid": 4,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 4
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 3
  }, {
    "source_gid": 6,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 3
  }, {
    "source_gid": 15,
    "target_gid": 3,
    "count": 6
  }, {
    "source_gid": 18,
    "target_gid": 14,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 2,
    "count": 10
  }, {
    "source_gid": 6,
    "target_gid": 2,
    "count": 5
  }, {
    "source_gid": 2,
    "target_gid": 2,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 8,
    "count": 4
  }, {
    "source_gid": 3,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 7,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 12,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 19,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 13,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 17,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 2,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 12,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 9,
    "target_gid": 9,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 5,
    "target_gid": 4,
    "count": 1
  }]
}, {
  "year": 1980,
  "flow": [{
    "source_gid": 15,
    "target_gid": 15,
    "count": 5607
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 66
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 99
  }, {
    "source_gid": 3,
    "target_gid": 15,
    "count": 10
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 311
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 288
  }, {
    "source_gid": 13,
    "target_gid": 13,
    "count": 107
  }, {
    "source_gid": 15,
    "target_gid": 16,
    "count": 74
  }, {
    "source_gid": 0,
    "target_gid": 16,
    "count": 11
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 84
  }, {
    "source_gid": 19,
    "target_gid": 19,
    "count": 40
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 459
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 96
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 42
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 184
  }, {
    "source_gid": 15,
    "target_gid": 18,
    "count": 18
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 3,
    "count": 16
  }, {
    "source_gid": 0,
    "target_gid": 3,
    "count": 4
  }, {
    "source_gid": 3,
    "target_gid": 3,
    "count": 28
  }, {
    "source_gid": 19,
    "target_gid": 7,
    "count": 13
  }, {
    "source_gid": 7,
    "target_gid": 7,
    "count": 23
  }, {
    "source_gid": 15,
    "target_gid": 7,
    "count": 20
  }, {
    "source_gid": 2,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 10,
    "count": 32
  }, {
    "source_gid": 17,
    "target_gid": 10,
    "count": 3
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 13
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 26
  }, {
    "source_gid": 11,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 86
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 25
  }, {
    "source_gid": 7,
    "target_gid": 18,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 1,
    "count": 3
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 27
  }, {
    "source_gid": 0,
    "target_gid": 19,
    "count": 26
  }, {
    "source_gid": 0,
    "target_gid": 14,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 15,
    "count": 61
  }, {
    "source_gid": 15,
    "target_gid": 19,
    "count": 96
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 10
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 10
  }, {
    "source_gid": 13,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 11,
    "count": 50
  }, {
    "source_gid": 15,
    "target_gid": 11,
    "count": 13
  }, {
    "source_gid": 1,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 7,
    "count": 7
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 15
  }, {
    "source_gid": 7,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 18
  }, {
    "source_gid": 18,
    "target_gid": 17,
    "count": 3
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 18,
    "count": 4
  }, {
    "source_gid": 6,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 13,
    "target_gid": 19,
    "count": 8
  }, {
    "source_gid": 2,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 13,
    "target_gid": 15,
    "count": 27
  }, {
    "source_gid": 5,
    "target_gid": 15,
    "count": 3
  }, {
    "source_gid": 0,
    "target_gid": 11,
    "count": 28
  }, {
    "source_gid": 11,
    "target_gid": 0,
    "count": 3
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 11
  }, {
    "source_gid": 15,
    "target_gid": 14,
    "count": 9
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 10
  }, {
    "source_gid": 1,
    "target_gid": 12,
    "count": 3
  }, {
    "source_gid": 15,
    "target_gid": 12,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 13,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 32
  }, {
    "source_gid": 18,
    "target_gid": 19,
    "count": 8
  }, {
    "source_gid": 17,
    "target_gid": 16,
    "count": 9
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 5
  }, {
    "source_gid": 18,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 11,
    "count": 2
  }, {
    "source_gid": 7,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 12
  }, {
    "source_gid": 0,
    "target_gid": 13,
    "count": 6
  }, {
    "source_gid": 15,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 24
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 14,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 7
  }, {
    "source_gid": 2,
    "target_gid": 15,
    "count": 5
  }, {
    "source_gid": 1,
    "target_gid": 10,
    "count": 15
  }, {
    "source_gid": 7,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 13,
    "count": 2
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 13
  }, {
    "source_gid": 16,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 13,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 17,
    "count": 3
  }, {
    "source_gid": 15,
    "target_gid": 17,
    "count": 7
  }, {
    "source_gid": 8,
    "target_gid": 19,
    "count": 3
  }, {
    "source_gid": 16,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 19,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 19,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 17,
    "count": 8
  }, {
    "source_gid": 17,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 1,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 3
  }, {
    "source_gid": 5,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 7,
    "count": 8
  }, {
    "source_gid": 1,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 2,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 7,
    "count": 4
  }]
}, {
  "year": 1990,
  "flow": [{
    "source_gid": 19,
    "target_gid": 15,
    "count": 69
  }, {
    "source_gid": 15,
    "target_gid": 15,
    "count": 6563
  }, {
    "source_gid": 13,
    "target_gid": 15,
    "count": 24
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 875
  }, {
    "source_gid": 13,
    "target_gid": 13,
    "count": 148
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 124
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 21
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 58
  }, {
    "source_gid": 19,
    "target_gid": 19,
    "count": 195
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 134
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 251
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 29
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 721
  }, {
    "source_gid": 14,
    "target_gid": 14,
    "count": 15
  }, {
    "source_gid": 15,
    "target_gid": 14,
    "count": 10
  }, {
    "source_gid": 11,
    "target_gid": 0,
    "count": 10
  }, {
    "source_gid": 0,
    "target_gid": 18,
    "count": 19
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 171
  }, {
    "source_gid": 8,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 6,
    "count": 25
  }, {
    "source_gid": 7,
    "target_gid": 6,
    "count": 3
  }, {
    "source_gid": 19,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 19,
    "count": 300
  }, {
    "source_gid": 8,
    "target_gid": 19,
    "count": 7
  }, {
    "source_gid": 3,
    "target_gid": 15,
    "count": 9
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 14
  }, {
    "source_gid": 11,
    "target_gid": 15,
    "count": 18
  }, {
    "source_gid": 15,
    "target_gid": 13,
    "count": 14
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 142
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 83
  }, {
    "source_gid": 18,
    "target_gid": 19,
    "count": 31
  }, {
    "source_gid": 16,
    "target_gid": 19,
    "count": 6
  }, {
    "source_gid": 14,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 19,
    "count": 4
  }, {
    "source_gid": 0,
    "target_gid": 19,
    "count": 40
  }, {
    "source_gid": 4,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 13,
    "target_gid": 19,
    "count": 20
  }, {
    "source_gid": 15,
    "target_gid": 17,
    "count": 9
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 58
  }, {
    "source_gid": 5,
    "target_gid": 15,
    "count": 9
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 8
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 33
  }, {
    "source_gid": 2,
    "target_gid": 15,
    "count": 7
  }, {
    "source_gid": 11,
    "target_gid": 11,
    "count": 67
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 42
  }, {
    "source_gid": 0,
    "target_gid": 14,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 59
  }, {
    "source_gid": 4,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 18,
    "count": 17
  }, {
    "source_gid": 4,
    "target_gid": 6,
    "count": 9
  }, {
    "source_gid": 0,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 6,
    "count": 9
  }, {
    "source_gid": 10,
    "target_gid": 6,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 14
  }, {
    "source_gid": 0,
    "target_gid": 11,
    "count": 25
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 4
  }, {
    "source_gid": 16,
    "target_gid": 17,
    "count": 2
  }, {
    "source_gid": 16,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 6
  }, {
    "source_gid": 5,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 53
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 3,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 10
  }, {
    "source_gid": 17,
    "target_gid": 16,
    "count": 11
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 4
  }, {
    "source_gid": 4,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 16,
    "count": 47
  }, {
    "source_gid": 17,
    "target_gid": 7,
    "count": 5
  }, {
    "source_gid": 0,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 7,
    "count": 6
  }, {
    "source_gid": 19,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 7
  }, {
    "source_gid": 15,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 19,
    "count": 7
  }, {
    "source_gid": 6,
    "target_gid": 19,
    "count": 7
  }, {
    "source_gid": 17,
    "target_gid": 13,
    "count": 2
  }, {
    "source_gid": 11,
    "target_gid": 1,
    "count": 4
  }, {
    "source_gid": 4,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 11,
    "count": 26
  }, {
    "source_gid": 0,
    "target_gid": 16,
    "count": 15
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 12
  }, {
    "source_gid": 13,
    "target_gid": 16,
    "count": 9
  }, {
    "source_gid": 15,
    "target_gid": 10,
    "count": 39
  }, {
    "source_gid": 1,
    "target_gid": 10,
    "count": 29
  }, {
    "source_gid": 1,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 16
  }, {
    "source_gid": 10,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 5,
    "count": 4
  }, {
    "source_gid": 13,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 3,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 3,
    "target_gid": 3,
    "count": 28
  }, {
    "source_gid": 1,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 0,
    "count": 3
  }, {
    "source_gid": 3,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 13,
    "count": 2
  }, {
    "source_gid": 16,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 15,
    "count": 3
  }, {
    "source_gid": 10,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 10,
    "count": 2
  }, {
    "source_gid": 16,
    "target_gid": 7,
    "count": 3
  }, {
    "source_gid": 15,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 7,
    "count": 7
  }, {
    "source_gid": 2,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 9,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 2,
    "target_gid": 19,
    "count": 7
  }, {
    "source_gid": 15,
    "target_gid": 3,
    "count": 5
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 17
  }, {
    "source_gid": 0,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 10,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 12
  }, {
    "source_gid": 18,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 9,
    "target_gid": 9,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 14,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 6,
    "target_gid": 4,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 8,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 19,
    "count": 2
  }, {
    "source_gid": 14,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 17,
    "count": 1
  }]
}, {
  "year": 2000,
  "flow": [{
    "source_gid": 15,
    "target_gid": 15,
    "count": 3453
  }, {
    "source_gid": 16,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 481
  }, {
    "source_gid": 7,
    "target_gid": 7,
    "count": 7
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 4
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 56
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 192
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 22
  }, {
    "source_gid": 13,
    "target_gid": 13,
    "count": 36
  }, {
    "source_gid": 0,
    "target_gid": 11,
    "count": 16
  }, {
    "source_gid": 11,
    "target_gid": 11,
    "count": 20
  }, {
    "source_gid": 15,
    "target_gid": 8,
    "count": 2
  }, {
    "source_gid": 19,
    "target_gid": 15,
    "count": 103
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 320
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 55
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 14
  }, {
    "source_gid": 19,
    "target_gid": 19,
    "count": 96
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 71
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 30
  }, {
    "source_gid": 15,
    "target_gid": 4,
    "count": 14
  }, {
    "source_gid": 4,
    "target_gid": 4,
    "count": 28
  }, {
    "source_gid": 8,
    "target_gid": 4,
    "count": 3
  }, {
    "source_gid": 6,
    "target_gid": 4,
    "count": 4
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 3
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 13
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 69
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 18
  }, {
    "source_gid": 11,
    "target_gid": 15,
    "count": 10
  }, {
    "source_gid": 15,
    "target_gid": 17,
    "count": 5
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 55
  }, {
    "source_gid": 18,
    "target_gid": 18,
    "count": 14
  }, {
    "source_gid": 2,
    "target_gid": 15,
    "count": 7
  }, {
    "source_gid": 13,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 3,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 14
  }, {
    "source_gid": 15,
    "target_gid": 13,
    "count": 3
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 17
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 18
  }, {
    "source_gid": 0,
    "target_gid": 18,
    "count": 9
  }, {
    "source_gid": 15,
    "target_gid": 18,
    "count": 11
  }, {
    "source_gid": 4,
    "target_gid": 18,
    "count": 7
  }, {
    "source_gid": 16,
    "target_gid": 18,
    "count": 2
  }, {
    "source_gid": 15,
    "target_gid": 10,
    "count": 4
  }, {
    "source_gid": 17,
    "target_gid": 16,
    "count": 4
  }, {
    "source_gid": 7,
    "target_gid": 17,
    "count": 2
  }, {
    "source_gid": 17,
    "target_gid": 17,
    "count": 3
  }, {
    "source_gid": 10,
    "target_gid": 17,
    "count": 3
  }, {
    "source_gid": 16,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 4,
    "count": 5
  }, {
    "source_gid": 7,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 0,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 0,
    "count": 6
  }, {
    "source_gid": 15,
    "target_gid": 11,
    "count": 15
  }, {
    "source_gid": 1,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 10,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 16,
    "count": 3
  }, {
    "source_gid": 15,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 17,
    "target_gid": 0,
    "count": 7
  }, {
    "source_gid": 13,
    "target_gid": 19,
    "count": 6
  }, {
    "source_gid": 0,
    "target_gid": 19,
    "count": 11
  }, {
    "source_gid": 15,
    "target_gid": 19,
    "count": 58
  }, {
    "source_gid": 5,
    "target_gid": 15,
    "count": 2
  }, {
    "source_gid": 3,
    "target_gid": 3,
    "count": 19
  }, {
    "source_gid": 8,
    "target_gid": 8,
    "count": 6
  }, {
    "source_gid": 7,
    "target_gid": 15,
    "count": 6
  }, {
    "source_gid": 10,
    "target_gid": 7,
    "count": 2
  }, {
    "source_gid": 18,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 2,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 11,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 19,
    "target_gid": 0,
    "count": 5
  }, {
    "source_gid": 16,
    "target_gid": 4,
    "count": 1
  }, {
    "source_gid": 17,
    "target_gid": 7,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 3,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 17,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 3,
    "count": 2
  }, {
    "source_gid": 12,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 2,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 8,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 16,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 19,
    "count": 1
  }]
}, {
  "year": 2010,
  "flow": [{
    "source_gid": 15,
    "target_gid": 15,
    "count": 390
  }, {
    "source_gid": 17,
    "target_gid": 15,
    "count": 5
  }, {
    "source_gid": 0,
    "target_gid": 15,
    "count": 65
  }, {
    "source_gid": 6,
    "target_gid": 2,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 10,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 4,
    "target_gid": 15,
    "count": 6
  }, {
    "source_gid": 16,
    "target_gid": 15,
    "count": 10
  }, {
    "source_gid": 1,
    "target_gid": 1,
    "count": 69
  }, {
    "source_gid": 0,
    "target_gid": 0,
    "count": 129
  }, {
    "source_gid": 11,
    "target_gid": 1,
    "count": 2
  }, {
    "source_gid": 19,
    "target_gid": 19,
    "count": 28
  }, {
    "source_gid": 15,
    "target_gid": 0,
    "count": 8
  }, {
    "source_gid": 15,
    "target_gid": 1,
    "count": 22
  }, {
    "source_gid": 0,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 1,
    "target_gid": 11,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 0,
    "count": 3
  }, {
    "source_gid": 0,
    "target_gid": 1,
    "count": 5
  }, {
    "source_gid": 14,
    "target_gid": 15,
    "count": 2
  }, {
    "source_gid": 6,
    "target_gid": 1,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 19,
    "count": 13
  }, {
    "source_gid": 6,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 15,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 7,
    "target_gid": 5,
    "count": 1
  }, {
    "source_gid": 19,
    "target_gid": 15,
    "count": 9
  }, {
    "source_gid": 10,
    "target_gid": 0,
    "count": 1
  }, {
    "source_gid": 13,
    "target_gid": 15,
    "count": 2
  }, {
    "source_gid": 0,
    "target_gid": 19,
    "count": 9
  }, {
    "source_gid": 1,
    "target_gid": 15,
    "count": 4
  }, {
    "source_gid": 10,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 4,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 15,
    "count": 1
  }, {
    "source_gid": 18,
    "target_gid": 15,
    "count": 2
  }, {
    "source_gid": 16,
    "target_gid": 16,
    "count": 6
  }, {
    "source_gid": 15,
    "target_gid": 16,
    "count": 2
  }, {
    "source_gid": 14,
    "target_gid": 0,
    "count": 2
  }, {
    "source_gid": 8,
    "target_gid": 19,
    "count": 1
  }, {
    "source_gid": 13,
    "target_gid": 0,
    "count": 3
  }]
}];


export default influenceByYear;